### ISSUE TITLE
Does pyjasper support Mongodb

### ISSUE THREAD

**Issue by soohan92** [PyReportJasper/pyreportjasper#23] opened 2017-12-07 07:12 UTC
I am trying to connect Mongodb from pyjasper. But I couldn't find any example which using Mongodb here. 

Is this library support Mongodb?

**Comment by jadsonbr** [comment] 2017-12-07 11:59
You should download the JDBC jar and put it in the `pyjasper/jasperstarter/jdbc/`

[Doc JDBC Configuration](https://github.com/jadsonbr/pyreport#note)

[Download JDBC MongoDB](https://mongodb.github.io/mongo-java-driver/)

**Comment by jadsonbr** [comment] 2018-03-07 20:09
If everything went well do not forget to close the issue.

**Comment by jwazne** [comment] 2018-04-09 20:03
Hi Jadson, 

I've just tested your solution but I ended with the following error:

java.lang.reflect.InvocationTargetException
...
Caused by: net.sf.jasperreports.engine.JRRuntimeException: No query executer factory registered for the "MongoDbQuery" language.

In my jrxml file I'm using MongoDbQuery as language for the datasource.

Does jasperstarter work with mongodbquery language ?

Thanks for your help !

Regards,

**Comment by jadsonbr** [comment] 2018-04-09 20:07
Did you put the JDBC Driver in the folder?

**Comment by jwazne** [comment] 2018-04-09 20:11
I'm using virtualenv so in the **venv/lib/python3.6/site-packages/pyjasper/jasperstarter/jdbc** folder I've put the **mongo-java-driver-3.6.3.jar** file

**Comment by jadsonbr** [comment] 2018-05-17 17:05
You can point to where the driver is by passing the resource parameter:

```python
jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf"],
        parameters={},
        db_connection=con,
        locale='en_US',
        resource='path/to/my/resource/mongo-java-driver-3.6.3.jar'
    )
```

**Comment by varun952** [comment] 2019-01-07 18:14
I am facing same issue, I tried using the code mentioned above, but it gives me following error : 
Unable to load driver: mongodb.jdbc.MongoDriver
Traceback (most recent call last):
  File "/home/ubuntu1604/eclipse-workspace1/Jasper_report_ver_007/report_1/Main.py", line 33, in <module>
    resource='/home/ubuntu1604/Downloads/mongodb-driver-sync-3.7.1.jar'
  File "/usr/local/lib/python2.7/dist-packages/pyreportjasper/jasperpy.py", line 151, in process
    return self.execute()
  File "/usr/local/lib/python2.7/dist-packages/pyreportjasper/jasperpy.py", line 190, in execute
    output = subprocess.check_call(self.command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/lib/python2.7/dist-packages/pyreportjasper/jasperstarter/bin/jasperstarter --locale en_US process "/home/ubuntu1604/JaspersoftWorkspace/MyReports/arun_Landscape.jasper" -o "/home/ubuntu1604" -f pdf -P  PARAM_1="hawkeye"   PARAM_2="onair"   -t generic --db-driver mongodb.jdbc.MongoDriver --db-url mongodb://user:pass@127.0.0.1:27017/db_name -r /home/ubuntu1604/Downloads/mongodb-driver-sync-3.7.1.jar' returned non-zero exit status 1

**Comment by jadsonbr** [comment] 2019-01-11 13:56
Mongodb support is not totally viable, I will be providing a version for proper operation with the same

**Comment by varun952** [comment] 2019-04-02 06:06
Any updates for MongoDB support? I am looking forward to it

**Comment by jadsonbr** [comment] 2019-11-13 12:49
@varun952 
Upon analysis at this time it will not be possible to implement mongoDB support.

[In the other version who knows in the future.](https://github.com/PyReportJasper/pyreportjasper2)

**Closed by jadsonbr** 2019-11-13 12:49 UTC
